<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

use Illuminate\Support\Facades\DB;

class ExportDataToSql extends Command
{
    protected $signature = 'export:sql {--output=data.sql} {--tables=* : Specific tables only, omit for all} {--batch-size=500 : Rows per INSERT statement}';
    protected $description = 'Export data from the MySQL/MariaDB connection as standard, batched SQL INSERT statements — works in phpMyAdmin, TablePlus, pgAdmin, etc, against MySQL/MariaDB or PostgreSQL';

    protected array $skip = [
        'migrations', 'failed_jobs', 'password_reset_tokens',
        'personal_access_tokens', 'sessions', 'cache', 'cache_locks',
        'jobs', 'job_batches',
    ];

    // Anything in here is written as a bare number. tinyint(1) is excluded —
    // it's treated as a boolean below instead.
    protected array $numericTypes = [
        'tinyint', 'smallint', 'mediumint', 'int', 'integer', 'bigint',
        'decimal', 'numeric', 'float', 'double', 'real',
    ];

    protected array $dateTypes = ['datetime', 'timestamp', 'date', 'time', 'year'];

    public function handle()
    {
        $database  = DB::connection('mysql')->getDatabaseName();
        $tables    = $this->option('tables') ?: $this->discoverTables($database);
        $path      = $this->option('output');
        $batchSize = max(1, (int) $this->option('batch-size'));
        $out       = fopen($path, 'w');

        fwrite($out, "-- Generated by export:sql on " . now()->toDateTimeString() . "\n");
        fwrite($out, "-- Plain batched INSERT statements — safe to run in MySQL, MariaDB or PostgreSQL.\n");
        fwrite($out, "-- If any text column contains backslashes and you're importing into MySQL, run this\n");
        fwrite($out, "-- first so quoting behaves the same as it does in PostgreSQL by default:\n");
        fwrite($out, "-- SET sql_mode = (SELECT CONCAT(@@sql_mode, ',NO_BACKSLASH_ESCAPES'));\n\n");

        $idColumns = [];

        foreach ($tables as $table) {
            $this->info("Exporting {$table}...");

            $columnInfo = DB::connection('mysql')->select(
                "SELECT COLUMN_NAME, DATA_TYPE, COLUMN_TYPE FROM information_schema.columns
                 WHERE table_schema = ? AND table_name = ? ORDER BY ORDINAL_POSITION",
                [$database, $table]
            );

            $colNames = collect($columnInfo)->pluck('COLUMN_NAME')->all();

            $boolCols = collect($columnInfo)
                ->filter(fn ($c) => $c->DATA_TYPE === 'tinyint' && str_contains($c->COLUMN_TYPE, '(1)'))
                ->pluck('COLUMN_NAME')->all();

            $numericCols = collect($columnInfo)
                ->filter(fn ($c) => in_array($c->DATA_TYPE, $this->numericTypes) && !in_array($c->COLUMN_NAME, $boolCols))
                ->pluck('COLUMN_NAME')->all();

            $dateCols = collect($columnInfo)
                ->whereIn('DATA_TYPE', $this->dateTypes)
                ->pluck('COLUMN_NAME')->all();

            if (in_array('id', $colNames)) {
                $idColumns[] = $table;
            }

            $colList  = implode(', ', $colNames);
            $rowCount = 0;

            fwrite($out, "-- Table: {$table}\n");

            DB::connection('mysql')->table($table)->orderByRaw('1')
                ->chunk($batchSize, function ($rows) use ($out, $table, $colNames, $colList, $boolCols, $numericCols, $dateCols, &$rowCount) {
                    if ($rows->isEmpty()) {
                        return;
                    }

                    $tuples = [];

                    foreach ($rows as $row) {
                        $row = (array) $row;
                        $fields = [];

                        foreach ($colNames as $col) {
                            $val = $row[$col] ?? null;

                            // MySQL's invalid zero-dates have no equivalent in Postgres — treat as NULL
                            if (in_array($col, $dateCols) && in_array($val, ['0000-00-00 00:00:00', '0000-00-00'], true)) {
                                $val = null;
                            }

                            $fields[] = $this->escapeValue(
                                $val,
                                in_array($col, $numericCols),
                                in_array($col, $boolCols)
                            );
                        }

                        $tuples[] = '(' . implode(', ', $fields) . ')';
                        $rowCount++;
                    }

                    fwrite($out, "INSERT INTO {$table} ({$colList}) VALUES\n" . implode(",\n", $tuples) . ";\n\n");
                });

            if ($rowCount === 0) {
                fwrite($out, "-- (no rows)\n\n");
            }
        }

        if (!empty($idColumns)) {
            fwrite($out, "\n-- ==============================================================\n");
            fwrite($out, "-- PostgreSQL only — uncomment and run after import if these tables\n");
            fwrite($out, "-- use SERIAL/IDENTITY id columns, so the next auto-generated id\n");
            fwrite($out, "-- doesn't collide with the ids you just imported. Skip this for\n");
            fwrite($out, "-- MySQL/MariaDB — AUTO_INCREMENT adjusts itself automatically.\n");
            fwrite($out, "-- ==============================================================\n");
            foreach ($idColumns as $table) {
                fwrite($out, "-- SELECT setval(pg_get_serial_sequence('{$table}', 'id'), COALESCE((SELECT MAX(id) FROM {$table}), 1));\n");
            }
        }

        fclose($out);

        $this->info("Done. Wrote " . count($tables) . " tables to {$path}");
    }

    /**
     * Standard SQL literal formatting — unmodified ANSI syntax, valid in
     * MySQL, MariaDB and PostgreSQL alike:
     *  - NULL is written as the bare keyword.
     *  - Numbers are written bare (unquoted).
     *  - Booleans are written as TRUE/FALSE — both engines accept these as
     *    native literals (MySQL treats them as synonyms for 1/0).
     *  - Everything else is quoted, with only single quotes doubled ('').
     *    Backslashes are left untouched — see the note at the top of the
     *    generated file about NO_BACKSLASH_ESCAPES for MySQL imports.
     */
    private function escapeValue($value, bool $isNumeric = false, bool $isBoolean = false): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if ($isBoolean) {
            return ((int) $value === 1) ? 'TRUE' : 'FALSE';
        }

        if ($isNumeric) {
            return is_numeric($value) ? (string) $value : 'NULL';
        }

        return "'" . str_replace("'", "''", (string) $value) . "'";
    }

    private function discoverTables(string $database): array
    {
        $rows = DB::connection('mysql')->select(
            "SELECT TABLE_NAME FROM information_schema.tables WHERE table_schema = ? AND table_type = 'BASE TABLE'",
            [$database]
        );

        return collect($rows)->pluck('TABLE_NAME')
            ->reject(fn ($t) => in_array($t, $this->skip))
            ->values()
            ->all();
    }
}
